version: '3'

services:
  demo-container:
    image: demo-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/demo-container
    ports:
      - "8080:8080"